MS = 1000000
S = 1000 * MS
MINE_RATE = 4 * S #4 Sekunden


PRIVATE_KEY = '''-----BEGIN PRIVATE KEY-----
MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgKK+7/F7WQA6JCRjN/ajp
M1tUoX9vTTlZF/yNAxP6KCehRANCAASeIlXBGveqgjI/Xvuy3NyGXv15aqHnGiDe
JTtADlFQnDL8WoNGVzFUuWbzZesHKrJsq7rzv/cObrktaV1ADSVd
-----END PRIVATE KEY-----'''

